name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: npm
        cache-dependency-path: helloworld/package-lock.json
    - run: cd helloworld && npm ci
