on: push
name: Script Test On Push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./helloworld/
      with:
        who-to-greet: |
          Akira
          Tetsuo
          Yamagata
    - uses: actions/github-scripts
      with:
        script: |
          const helloworld = require('./helloworld')
          helloworld()
