on: push
permissions:
  checks: write
name: Script Test On Push
jobs:
  test:
    runs-on: ubuntu-latest
    #strategy:
    #  matrix:
    #    batch: [1, 2]
    steps:
    - uses: actions/checkout@master
    - uses: actions/github-script@v6
      with:
        script: |
          const repo = context.payload.repository
          const res = await github.rest.checks.create({
            owner: repo.owner.login,
            repo: repo.name,
            head_sha: context.sha,
            name: 'Choooissu',
            status: 'in_progress'
          })
          console.dir(res)
    - uses: ./helloworld
      with:
        who-to-greet: |
          Akira
          Tetsuo
          Yamagata
    - uses: actions/github-script@v6
      with:
        script: |
          console.dir({ context, github })
          console.dir(context.payload)
          const helloworld = require('./helloworld')
          helloworld({core,glob,process})
          const repo = context.payload.repository
          const summary = `
            # this is summary
            - sum
            - ary
          `
          const text = `# kottiha text
           - ittai
           - dou chigau
          `
          github.rest.checks.update({
            owner: repo.owner.login,
            repo: repo.name,
            head_sha: context.sha,
            name: 'Choooissu',
            title: 'titliii',
            status: 'completed',
            conclusion: 'success',
            output: {
              title: 'ok ok title da',
              summary: summary,
              text: text
            }
          })
    - if: always()
      run: |
        echo "::set-output name=message::Test A ${{ (job.status == 'success' && '✅') || '❌' }}"
        echo "# Summary for Test ${{ matrix.batch }}" >> $GITHUB_STEP_SUMMARY
        echo "- Test ${{ matrix.batch }}" >> $GITHUB_STEP_SUMMARY
