on: push
name: push-note
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        id: dump
        with:
          script: |
            console.log({ github, context })
      - run: npm ci
      - run: npm test
      - run: |
          echo "::error file=package.json,line=2,col=5,endColumn=7,title=I don't like this title::Missing semicolon
          foo bar
          wrong"
  perltest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.34'
          install-modules-with: cpanm
          install-modules-args: --with-develop --with-configure
      - run: npm run perltest
