on: push
name: Script Test On Push
jobs:
  test:
    runs-on: ubuntu-latest
    #strategy:
    #  matrix:
    #    batch: [1, 2]
    steps:
    - uses: actions/checkout@master
    - uses: ./helloworld
      with:
        who-to-greet: |
          Akira
          Tetsuo
          Yamagata
    - uses: actions/github-script@v6
      env:
        CHECK_ID: ${{steps.create_checks.outputs.result}}
      with:
        script: |
          console.dir({ context, github })
          console.dir(context.payload)
          const helloworld = require('./helloworld')
          const [ summary, text ] = helloworld({core,glob,process})
          const repo = context.payload.repository
          const { CHECK_ID } = process.env
          `
          const payload = {
            owner: repo.owner.login,
            repo: repo.name,
            check_run_id: CHECK_ID,
            name: 'Choooissu',
            title: 'titliii',
            status: 'completed',
            conclusion: 'success',
            output: {
              title: 'ok ok title da',
              summary: summary,
              text: text
            }
          }
          console.dir(payload)
          github.rest.checks.update(payload)
    - if: always()
      run: |
        echo "::set-output name=message::Test A ${{ (job.status == 'success' && '✅') || '❌' }}"
        echo "# Summary for Test ${{ matrix.batch }}" >> $GITHUB_STEP_SUMMARY
        echo "- Test ${{ matrix.batch }}" >> $GITHUB_STEP_SUMMARY
