on: push
name: Script Test On Push
jobs:
  reuse:
    uses: ./.github/workflows/reuse.yml
  test:
    runs-on: ubuntu-latest
    steps:
    - run: whoami
    - run: echo "refname ${{ github.ref_name }}"
    - run: echo "${{ toJSON( github ) }}"
      name: Dump github
    - uses: actions/checkout@master
    - name: print secret
      env:
        pn: ${{ secrets.PRIVATE_NAME }}
      run: |
        echo "$pn"
        echo $pn | wc -c
    - uses: actions/github-script@v6
      name: dump
      with:
        script: |
          console.dir( context, { depth: null } )
          console.dir( github, { depth: null } )
    - run: |
        echo "::set-output name=message::Test A ${{ (job.status == 'success' && '✅') || '❌' }}"
        echo "# Summary for Test ${{ matrix.batch }}" >> $GITHUB_STEP_SUMMARY
        echo "- Test ${{ matrix.batch }}" >> $GITHUB_STEP_SUMMARY
