on: push
name: push-note
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - uses: actions/github-script@v6
        id: dump
        with:
          script: |
            console.log({ github, context })
      - run: npm ci
      - run: npm run test:ci
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.34'
          install-modules-with: cpanm
          install-modules-args: --with-develop --with-configure
      - env:
          PERL_TEST_HARNESS_DUMP_TAP: ./tapout/
        run: |
          npm run perltest || true &> /dev/null
          ls
          pwd
      - run: ls $GITHUB_WORKSPACE/tapout/t
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'tapout/t/*.xml'
