on: push
name: Script Test On Push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        batch: [1, 2]
    steps:
    - uses: actions/checkout@master
    - uses: ./helloworld
      with:
        who-to-greet: |
          Akira
          Tetsuo
          Yamagata
    - uses: actions/github-script@v6
      with:
        script: |
          console.dir({strategy, matrix})
          const helloworld = require('./helloworld')
          helloworld({core,glob,process})
