on: push
name: Script Test On Push
jobs:
  reuse:
    uses: ./.github/workflows/reuse.yml
    secrets: inherit
  test:
    runs-on: ubuntu-latest
    steps:
    - run: whoami
    - if: env.foo.bar.buzz || always()
      run: echo "Can I run?"
    - run: arch
    - run: echo "refname ${{ github.ref_name }}"
    - run: echo "${{ toJSON( github ) }}"
      name: Dump github
    - uses: actions/checkout@master
    - env:
        true1: ${{ 1 == true }}
        true2: ${{ 'true' == true }}
      run: |
        echo "$true1"
        if [ "$true1" = 'true' ]; then
          echo "true1 is true"
        fi

        echo "$true2"
        if [ "$true2" = 'true' ]; then
          echo "true2 is true"
        fi
    - name: print secret
      env:
        pn: ${{ secrets.PRIVATE_NAME }}
      run: |
        echo "$pn"
        echo $pn | wc -c
    - uses: actions/github-script@v6
      name: dump
      with:
        script: |
          console.dir( context, { depth: null } )
          console.dir( github, { depth: null } )
    - run: |
        echo "::set-output name=message::Test A ${{ (job.status == 'success' && '✅') || '❌' }}"
        echo "# Summary for Test ${{ matrix.batch }}" >> $GITHUB_STEP_SUMMARY
        echo "- Test ${{ matrix.batch }}" >> $GITHUB_STEP_SUMMARY
