on: push
name: push-note
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        id: dump
        with:
          script: |
            console.log({ github, context })
      - run: npm ci
      - run: npm test
  perltest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm run perltest
