on: push
permissions:
  checks: write
name: Script Test On Push
jobs:
  test:
    runs-on: ubuntu-latest
    #strategy:
    #  matrix:
    #    batch: [1, 2]
    steps:
    - uses: actions/checkout@master
    - uses: ./helloworld
      with:
        who-to-greet: |
          Akira
          Tetsuo
          Yamagata
    - uses: actions/github-script@v6
      with:
        script: |
          console.dir({ context, github })
          console.dir(context.payload)
          const helloworld = require('./helloworld')
          helloworld({core,glob,process})
          const repo = context.payload.repository
          github.rest.checks.create({
            owner: repo.owner.login,
            repo: repo.name,
            head_sha: context.sha,
            name: 'Choooissu',
            title: 'titliii',
            summary: `# this is
            summary desu
             - hoge
             - moge
            `
          })
    - if: always()
      run: |
        echo "::set-output name=message::Test A ${{ (job.status == 'success' && '✅') || '❌' }}"
        echo "# Summary for Test ${{ matrix.batch }}" >> $GITHUB_STEP_SUMMARY
        echo "- Test ${{ matrix.batch }}" >> $GITHUB_STEP_SUMMARY
