on: push
name: Script Test On Push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        batch: [1, 2]
    steps:
    - uses: actions/checkout@master
    - uses: ./helloworld
      with:
        who-to-greet: |
          Akira
          Tetsuo
          Yamagata
    - uses: actions/github-script@v6
      with:
        script: |
          console.dir('mat',context.matrix)
          const helloworld = require('./helloworld')
          helloworld({core,glob,process})
    - if: always()
      run: |
        echo "::set-output name=message::Test A ${{ (job.status == 'success' && '✅') || '❌' }}"
        echo "# Summary for Test ${{ matrix.batch }}" >> $GITHUB_STEP_SUMMARY
        echo "- Test ${{ matrix.batch }}" >> $GITHUB_STEP_SUMMARY
