on: issue_comment
name: comment reply
jobs:
  print-username:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: check-dev-label
        with:
          script: |
            const isPeasyDev = context.payload.issue.labels
              .filter( l => l.name === 'workflow-dev' ).length ? true : false
            return isPeasyDev
      - uses: actions/github-script@v6
        id: check-pr-ref
        result-encoding: string
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.issue.number
            } )
            return pr.data.head.ref
      - name: Print the input name to STDOUT
        run: echo if ${{ steps.check-dev-label.outputs.result }} then ${{ steps.check-pr-ref.outputs.result }}

      - uses: actions/checkout@v3
        if: ${{ steps.check-dev-label.outputs.result }}
        with:
          ref: ${{ steps.check-pr-ref.outputs.result }}
      - name: Print repo
        run: cd $GITHUB_WORKSPACE && ls
