on: issue_comment
name: comment reply
jobs:

  print-username:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v6
        id: dump
        with:
          script: console.log(context.payload.issue.pull_request)
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.username }}
