on: issue_comment
name: comment reply
jobs:
  print-username:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: dump
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.issue.number
            } )
            const pr_ref = pr.data.head.ref
            console.log('from pull request', pr_ref)
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.username }}

