on: issue_comment
name: comment reply
jobs:
  print-username:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: check-pr-ref
        with:
          result-encoding: string
          script: |
            const hasDeployLabel = context.payload.issue.labels
             .filter( l => l.name === 'Type:Deployment' ).length ? 1 : 0
            if ( !hasDeployLabel ) {
              console.log("Going to check out from [master] branch...")
              return 'main'
            }

            console.log('Got Type:Deployment label')
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.issue.number
            })
            const ref = pr.data.head.ref
            console.log("Going to check out from [" + ref + "] branch...")
            return ref
      - name: Print the input name to STDOUT
        run: echo if ${{ steps.check-dev-label.outputs.result }} then ${{ steps.check-pr-ref.outputs.result }}

      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.check-pr-ref.outputs.result }}
      - name: Print repo
        run: cd $GITHUB_WORKSPACE && ls
