on: issue_comment
name: comment reply
jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:
      - name: detect branch
        run: pwd && ls && $GITHUB_WORKSPACE/detect-branch.sh
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.username }}
