on: issue_comment
name: comment reply
jobs:

  print-username:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v6
        id: dump
        with:
          script: console.log( github.rest.pulls.get( ...context.payload.repository.fullname.split('/'), context.payload.issue.number ))
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.username }}
