name: deploy
on:
  deployment
  deployment_status
jobs:
  deploy:
    name: DEPLOY ${{ github.event.deployment.environment }} ${{ github.event.deployment.task }}
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run:  echo "Execute the deproy script here."
      - uses: actions/github-script@v6
        with:
          script: |
            console.dir( context, { depth: null } )

