name: dispatch3
on:
  workflow_dispatch:
    inputs:
      pr-ref:
        required: true
        type: string

  workflow_call:
    inputs:
      pr-ref:
        required: true
        type: string

  # For debug purpose. Remove before merge this.
  push:

jobs:
  howtheywork:
    # debug
    runs-on: ubuntu-latest
    name: 'Check workflow'
    env:
      pr-ref: ${{ inputs.pr-ref }}
    steps:
      - name: Fetch PR ref
        run: echo "${{ toJSON( github ) }}"
      - run: echo "hello2"


