name: dispatch3
on:
  workflow_dispatch:

  workflow_call:
    inputs:
      pr-ref:
        required: true
        type: string

  # For debug purpose. Remove before merge this.
  push:

jobs:
  howtheywork:
    # debug
    runs-on: ubuntu-latest
    name: 'Check workflow'
    env:
      pr-ref: ${{ inputs.pr-ref }}
    steps:
      - if: ${{ ! env.pr-ref }}
        run: echo "pr-ref=${{ github.event.ref_name }}" >> $GITHUB_ENV
      - run: echo "hello2 ${{ env.pr-ref }}"


