name: dispatch3
on:
  workflow_dispatch:

  workflow_call:
    inputs:
      ref_name:
        required: true
        type: string

  # For debug purpose. Remove before merge this.
  push:

jobs:
  howtheywork:
    # debug
    runs-on: ubuntu-latest
    name: 'Check workflow'
    env:
      ref_name: ${{ inputs.ref_name }}
    steps:
      - if: ${{ ! env.ref_name }}
        run: echo "ref_name=${{ github.ref_name }}" >> $GITHUB_ENV
      - run: echo "hello2 ${{ env.ref_name }}"


