name: Multi event handling
on:
  issue_comment:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - run: echo "event is the ${{ github.event_name }}"
    - run: echo '${{ toJSON(github) }}'
