on: issue_comment
name: comment run
jobs:
  parse:
    name: Comment Parser
    runs-on: ubuntu-latest
    outputs:
      action: ${{ env.action }}
      ref: ${{ steps.check-pr.outputs.ref }}
    env:
      body: ${{ github.event.comment.body }}
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            console.dir( context, { depth: null })
      - run: echo "greeting ${{ github.event.comment.user.login }}"
      - uses: actions/github-script@v6
        id: pr-info
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.issue.number
            })
            console.dir(pr, { depth: null })
      - run: |
          echo "ppull ${{ toJSON(github) }}"
        name: Dump
      - if: startsWith( env.body, '!deploy')
        run: echo "action=deploy" >> $GITHUB_ENV

      - if: startsWith( env.body, '!test')
        run: echo "action=test" >> $GITHUB_ENV

      - run: echo "No action"
        if: ${{ ! env.action }}

      - run: echo "has Action"
        if: ${{ env.action }}
      - run: echo "Action is " $the_action
        env:
          the_action: ${{ env.action }}
      - run: echo "No action 2"
        if: ${{ ! env.action }}

      - run: echo "has Action 2"
        if: ${{ env.action }}
      - run: echo "Action is " $the_action
        env:
          the_action: ${{ env.action }}
      - run: echo "hogeee"
        name: final
      - uses: actions/github-script@v6
        id: check-pr
        if: github.event.issue.pull_request
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.issue.number
            })
            core.setOutput('ref', pr.data.head.ref)
            core.setOutput('sha', pr.data.head.sha)
  deploy:
    needs: parse
    if: needs.parse.outputs.action == 'deploy'
    uses: ./.github/workflows/dispatch.yml
    with:
      ref_name: main
  test:
    needs: parse
    runs-on: ubuntu-latest
    if: needs.parse.outputs.action == 'test'
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}
          ref: ${{ needs.parse.outputs.ref }}
      - run: |
          echo "${{ github.event.comment.body }}" >> comments.txt
          git add comments.txt
          git config user.name "${{ github.event.comment.user.login }}"
          git config user.email "aklaswad@gmail.com"
          git commit -m "from comment"
          git push origin ${{ needs.parse.outputs.ref }}

