on: issue_comment
name: comment run
jobs:
  parseOn:
    name: Comment Parser
    runs-on: ubuntu-latest
    outputs:
      action: ${{ env.action }}
    env:
      body: ${{ github.event.comment.body }}
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            console.dir( context, { depth: null })
      - run: echo "greeting ${{ github.event.comment.user.login }}"
      - uses: actions/github-script@v6
        id: pr-info
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.issue.number
            })
            console.dir(pr, { depth: null })
      - run: |
          echo "ppull ${{ toJSON(github.event.issue.pull_request) }}"
      - if: startsWith( env.body, '!deploy')
        run: echo "action=deploy" >> $GITHUB_ENV

      - if: startsWith( env.body, '!test')
        run: echo "action=test" >> $GITHUB_ENV

      - run: echo "No action"
        if: ${{ ! env.action }}

      - run: echo "has Action"
        if: ${{ env.action }}
      - run: echo "Action is " $the_action
        env:
          the_action: ${{ env.action }}
      - run: echo "No action 2"
        if: ${{ ! env.action }}

      - run: echo "has Action 2"
        if: ${{ env.action }}
      - run: echo "Action is " $the_action
        env:
          the_action: ${{ env.action }}
      - run: echo "hogeee"
        name: final
  deploy:
    needs: parseOn
    runs-on: ubuntu-latest
    if: needs.parseOn.outputs.action == 'deploy'
    steps:
      - run: echo "deploy!"
      - uses: ./.github/workflows/dispatch.yml
        with:
          ref_name: main
        name: Run dispatch
      - uses: actions/github-script@v6
        with:
          script: |
            const res = await github.rest.repos.createDeployment({
              owner: 'aklaswad',
              repo: 'wf-test',
              ref: 'main',
              environment: 'testing',
              description: 'Deploy from comment'

            })
            console.dir(res, { depth: null })
  test:
    needs: parseOn
    runs-on: ubuntu-latest
    if: needs.parseOn.outputs.action == 'test'
    steps:
      - run: echo "test..."
