on: issue_comment
name: comment test
jobs:
  parse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: parse
        name: Parse command from issue comment
        with:
          result-encoding: string
          script: |
            const comment = context.payload.comment.body
            if ( ! /^!/.test(comment) ) {
              // It's not command.
              return
            }
            const [ command, token ] = comment.substr(1).split(':')
            if ( command === 'alt-deploy-to-stating' ) {
              return 'deploy-staging'
            }
            return 'deploy-legacy'
  deploy-staging:
    runs-on: [ self-hosted, deploy-staging ]
    if: jobs.parse.steps.parse.outputs.result == 'deploy-staging'
    steps:
      - run: echo "deploy-staging"
  deploy-legacy:
    runs-on: ubuntu-latest
    if: jobs.parse.steps.parse.outputs.result == 'deploy-legacy'
    steps:
      - run: echo "deploy-legacy"

