on: issue_comment
name: comment test
jobs:
  parse:
    runs-on: ubuntu-latest
    outputs:
      command: ${{ fromJSON( steps.parse.outputs.result ).command }}
      token: ${{ fromJSON( steps.parse.outputs.result ).token }}
      runner: ${{ fromJSON( steps.parse.outputs.result ).runner }}
    steps:
      - uses: actions/github-script@v6
        id: parse
        name: Parse command from issue comment
        with:
          script: |
            const comment = context.payload.comment.body
            if ( ! /^!/.test(comment) ) {
              // It's not command.
              return
            }
            const [ command, token ] = comment.substr(1).split(':')
            if ( command === 'alt-deploy-to-staging' ) {
              return {
                command: 'deploy-staging',
                token: token,
                runner: '[ self-hosted, private ]'
              }
            }
            return {
              command: 'deploy-legacy',
              token: token,
              runner: 'ubuntu-latest',
            }
  deploy-staging:
    runs-on: ${{ needs.parse.outputs.runner }}
    needs: parse
    if: needs.parse.outputs.command == 'deploy-staging'
    steps:
      - run: echo "deploy-staging"
  deploy-legacy:
    runs-on: ${{ needs.parse.outputs.runner }}
    needs: parse
    if: needs.parse.outputs.command == 'deploy-legacy'
    steps:
      -
        run: |
          echo "deploy-legacy"
          echo got ${{needs.parse.outputs.results}}
  dump:
    runs-on: ubuntu-latest
    needs: parse
    steps:
      - run: echo ${{needs.parse.outputs.command}}  ${{needs.parse.outputs.token}} got

