on: issue_comment
name: comment test
jobs:
  print-username:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: check-pr-ref
        name: dump comment
        with:
          result-encoding: string
          script: |
            const comment = context.payload.comment
            const issue = context.payload.issue
            const repo = context.payload.repo
            const sender = context.payload.sender

            console.log({ comment, issue, repo, sender })
