on:
  issue_comment:
  workflow_dispatch:
name: comment run
permissions:
  contents: write
jobs:
  parse:
    name: Comment Parser
    runs-on: ubuntu-latest
    outputs:
      action: ${{ env.action }}
      ref: ${{ steps.check-pr.outputs.ref }}
    env:
      body: ${{ github.event.comment.body }}
    steps:
      - run: echo refname "${{ github.ref_name }}"
      - run: echo ref_name $GITHUB_REF_NAME
      - run: echo hello
      - uses: actions/github-script@v6
        with:
          script: |
            console.dir( context, { depth: null })

      - uses: actions/checkout@v3
      - run: echo refname "${{ github.ref_name }}"
      - name: Fetch PR info
        id: pr
        if: ${{ ! github.event.issue || github.event.issue.pull_request }}
        env:
          GH_TOKEN: ${{ github.token }}
          PR_ID: ${{ github.event.issue.number || github.ref_name }}
        run: |
          echo "Fetch PR for $PR_ID"
          json="$(gh pr view --json number,labels,headRefName,title,url "$PR_ID" -q '.')"
          echo "$json"
          echo "ref=$(echo "$json" | jq -r '.headRefName')" >> $GITHUB_OUTPUT
          echo "url=$(echo "$json" | jq -r '.url')" >> $GITHUB_OUTPUT
          echo "number=$(echo "$json" | jq -r '.number')" >> $GITHUB_OUTPUT
          echo "title=$(echo "$json" | jq -r '.title')" >> $GITHUB_OUTPUT
          labels="$(echo "$json" | jq -c '.labels | map(.name)')"
          echo "labels ... $labels"
          echo "labels=$labels" >> $GITHUB_OUTPUT
      - run: |
          echo '
            ref    "${{ steps.pr.outputs.ref }}"
            url    "${{ steps.pr.outputs.url }}"
            number "${{ steps.pr.outputs.number }}"
            title  "${{ steps.pr.outputs.title }}"
            labels "${{ steps.pr.outputs.labels }}"
          '
      - run: echo "greeting ${{ github.event.comment.user.login }}"
      - uses: actions/github-script@v6
        id: pr-info
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.issue.number
            })
            console.dir(pr, { depth: null })
      - run: |
          echo "ppull ${{ toJSON(github) }}"
        name: Dump
      - if: startsWith( env.body, '!deploy')
        run: echo "action=deploy" >> $GITHUB_ENV

      - if: startsWith( env.body, '!test')
        run: echo "action=test" >> $GITHUB_ENV

      - run: echo "No action"
        if: ${{ ! env.action }}

      - run: echo "has Action"
        if: ${{ env.action }}
      - run: echo "Action is " $the_action
        env:
          the_action: ${{ env.action }}
      - run: echo "No action 2"
        if: ${{ ! env.action }}

      - run: echo "has Action 2"
        if: ${{ env.action }}
      - run: echo "Action is " $the_action
        env:
          the_action: ${{ env.action }}
      - run: echo "hogeee"
        name: final
      - uses: actions/github-script@v6
        id: check-pr
        if: github.event.issue.pull_request
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.issue.number
            })
            core.setOutput('ref', pr.data.head.ref)
            core.setOutput('sha', pr.data.head.sha)
  deploy:
    needs: parse
    if: needs.parse.outputs.action == 'deploy'
    uses: ./.github/workflows/dispatch.yml
    with:
      ref_name: main
  test:
    needs: parse
    runs-on: ubuntu-latest
    if: needs.parse.outputs.action == 'test'
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
          ref: ${{ needs.parse.outputs.ref }}
      - run: |
          echo "${{ github.event.comment.body }}" >> comments.txt
          git add comments.txt
          git config user.name "${{ github.event.comment.user.login }}"
          git config user.email "aklaswad@gmail.com"
          git commit -m "from comment"
          git push origin ${{ needs.parse.outputs.ref }}

