on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: echo "${{ toJSON( github ) }}"
    - run: echo refname "${{ github.ref_name }}"
    - run: echo ref_name $GITHUB_REF_NAME
    - uses: actions/checkout@v3
    - name: Merge?
      run: |
        git log -1
        git diff
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: HEAD
      run: |
        git log -1
        git diff


