on:
  push:
    branches:
      - main
jobs:
  update-master:
    runs-on: ubuntu-latest
    steps:
      - run: cat $GITHUB_EVENT_PATH
      - uses: actions/github-script@v6
        with:
          script: |
            console.dir(context.payload, {depth: null})

            const res = await github.request(`GET /repos/aklaswad/wf-test/commits/${context.payload.after}/pulls`, {
              owner: 'aklaswad',
              repo: 'wf-test',
              commit_sha: context.payload.after,
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            })
            if ( res ) {
              core.exportVariable('pullNumber', res.number)
              core.exportVariable('pullTitle', res.title)
            }
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(process.env.mergedBranch)
