name: Release package

on:
  release:
    types:
      - published
env:
  package: ${{ format('{0}-{1}', github.event.repository.name, github.event.release.name) }}

jobs:
  upload-asset:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          path: ${{ env.package }}
      - name: Debug
        run: ls -laR
      - name: Set up Node
        uses: actions/setup-node@v3
      - name: Build
        env:
          package: ${{ env.package }}
        run: |
          cd "$package"
          touch released.txt
          cd ../
          zip -r "${package}.zip" "${package}/"
      - name: debug
        run: |
          ls -laR
          cat $GITHUB_EVENT_PATH

      - name: Upload asset
        env:
          token: ${{ github.token }}
          package: ${{ env.package }}
          url: ${{ github.event.release.upload_url }}
        run: |
          upload_url="${url%%\{*}?name=${package}.zip"
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${token}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "Content-Type: application/zip" \
          "$upload_url" \
          --data-binary "@${package}.zip"
