name: Reuse
on:
  workflow_call:
jobs:
  reused:
    runs-on: ubuntu-latest
    steps:
    - run: echo hello reuse-dev
    - name: print secret
      env:
        pn: ${{ secrets.PRIVATE_NAME }}
      run: |
        echo "$pn"
        echo $pn | wc -c
