name: Run test

on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: test/test.sh
      - uses: actions/github-script@v6
        with:
          script: |
            console.dir(context)
            console.dir(context.payload)
